In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
#Load model
k = tf.keras.models.load_model('s_a_kn.h5')
w = tf.keras.models.load_model('s_a_wn.h5')
p = tf.keras.models.load_model('s_a_pn.h5')
f = tf.keras.models.load_model('s_a_fn.h5')

In [3]:
#load dataset after preprocessing
d = pd.read_csv('data_ap_s_a.csv')

In [4]:
#load data test after preprocessing
t = pd.read_csv('tes.csv')
tv = pd.read_csv('v.csv')

In [5]:
# Kuliner
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(d['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tv['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = k.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tv['kuliner'], rounded_predictions)
report = classification_report(tv['kuliner'], rounded_predictions)
cm = confusion_matrix(tv['kuliner'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8163265306122449
[[37  8]
 [ 1  3]]
              precision    recall  f1-score   support

           0       0.97      0.82      0.89        45
           1       0.27      0.75      0.40         4

    accuracy                           0.82        49
   macro avg       0.62      0.79      0.65        49
weighted avg       0.92      0.82      0.85        49



In [6]:
# Wahana
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(d['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tv['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = w.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tv['wahana'], rounded_predictions)
report = classification_report(tv['wahana'], rounded_predictions)
cm = confusion_matrix(tv['wahana'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8775510204081632
[[36  5]
 [ 1  7]]
              precision    recall  f1-score   support

           0       0.97      0.88      0.92        41
           1       0.58      0.88      0.70         8

    accuracy                           0.88        49
   macro avg       0.78      0.88      0.81        49
weighted avg       0.91      0.88      0.89        49



In [7]:
# Pelayanan
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(d['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tv['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = p.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tv['pelayanan'], rounded_predictions)
report = classification_report(tv['pelayanan'], rounded_predictions)
cm = confusion_matrix(tv['pelayanan'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[49]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        49

    accuracy                           1.00        49
   macro avg       1.00      1.00      1.00        49
weighted avg       1.00      1.00      1.00        49



In [8]:
# Fasilitas
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(d['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tv['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = f.predict(X)
rounded_predictions = np.round(predictions).astype(int)


accuracy = accuracy_score(tv['fasilitas'], rounded_predictions)
report = classification_report(tv['fasilitas'], rounded_predictions)
cm = confusion_matrix(tv['fasilitas'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.7551020408163265
[[28  3]
 [ 9  9]]
              precision    recall  f1-score   support

           0       0.76      0.90      0.82        31
           1       0.75      0.50      0.60        18

    accuracy                           0.76        49
   macro avg       0.75      0.70      0.71        49
weighted avg       0.75      0.76      0.74        49

