In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
#Load model
na = tf.keras.models.load_model('n_a_t.h5')
ns = tf.keras.models.load_model('n_s_t.h5')
sa = tf.keras.models.load_model('s_a_t.h5')
ss = tf.keras.models.load_model('s_s_t.h5')

In [3]:
#load dataset after preprocessing
dna = pd.read_csv('d_na_t.csv')
dns = pd.read_csv('d_ns_t.csv')
dsa = pd.read_csv('d_sa_t.csv')
dss = pd.read_csv('d_ss_t.csv')

In [4]:
#load data test after preprocessing
tna = pd.read_csv('vt_na.csv')
tns = pd.read_csv('vt_ns.csv')
tsa = pd.read_csv('vt_sa.csv')
tss = pd.read_csv('vt_ss.csv')

In [5]:
# NA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dna['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tna['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = na.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tna['label'], rounded_predictions)
report = classification_report(tna['label'], rounded_predictions)
cm = confusion_matrix(tna['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8080808080808081
[[15  9]
 [10 65]]
              precision    recall  f1-score   support

           0       0.60      0.62      0.61        24
           1       0.88      0.87      0.87        75

    accuracy                           0.81        99
   macro avg       0.74      0.75      0.74        99
weighted avg       0.81      0.81      0.81        99



In [6]:
# NS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dns['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tns['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ns.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tns['label'], rounded_predictions)
report = classification_report(tns['label'], rounded_predictions)
cm = confusion_matrix(tns['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8282828282828283
[[12 12]
 [ 5 70]]
              precision    recall  f1-score   support

           0       0.71      0.50      0.59        24
           1       0.85      0.93      0.89        75

    accuracy                           0.83        99
   macro avg       0.78      0.72      0.74        99
weighted avg       0.82      0.83      0.82        99



In [7]:
# SA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['label'], rounded_predictions)
report = classification_report(tsa['label'], rounded_predictions)
cm = confusion_matrix(tsa['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9292929292929293
[[22  2]
 [ 5 70]]
              precision    recall  f1-score   support

           0       0.81      0.92      0.86        24
           1       0.97      0.93      0.95        75

    accuracy                           0.93        99
   macro avg       0.89      0.93      0.91        99
weighted avg       0.93      0.93      0.93        99



In [8]:
# SA
# Preprocess data
ts = ["Tempat nya bersih", "panas tidak tenda", "wisat tutup hujan becek", "bumdes ramah"]
t=[1,0,0,1]
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(ts)
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(t, rounded_predictions)
report = classification_report(t, rounded_predictions)
cm = confusion_matrix(t, rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[2 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [9]:
# SS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dss['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tss['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ss.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tss['label'], rounded_predictions)
report = classification_report(tss['label'], rounded_predictions)
cm = confusion_matrix(tss['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9595959595959596
[[23  1]
 [ 3 72]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92        24
           1       0.99      0.96      0.97        75

    accuracy                           0.96        99
   macro avg       0.94      0.96      0.95        99
weighted avg       0.96      0.96      0.96        99

