In [20]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [28]:
#Load model
na = tf.keras.models.load_model('n_a.h5')
ns = tf.keras.models.load_model('n_s.h5')
sa = tf.keras.models.load_model('s_a.h5')
ss = tf.keras.models.load_model('s_s.h5')

In [29]:
#load dataset after preprocessing
dna = pd.read_csv('data_ap_n_a.csv')
dns = pd.read_csv('data_ap_n_s.csv')
dsa = pd.read_csv('data_ap_s_a.csv')
dss = pd.read_csv('data_ap_s_s.csv')

In [30]:
#load data test after preprocessing
tna = pd.read_csv('try_ap_n_a.csv')
tns = pd.read_csv('try_ap_n_s.csv')
tsa = pd.read_csv('try_ap_s_a.csv')
tss = pd.read_csv('try_ap_s_s.csv')

In [31]:
# NA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dna['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tna['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = na.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tna['label'], rounded_predictions)
report = classification_report(tna['label'], rounded_predictions)
cm = confusion_matrix(tna['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8333333333333334
[[ 3  2]
 [ 1 12]]
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.86      0.92      0.89        13

    accuracy                           0.83        18
   macro avg       0.80      0.76      0.78        18
weighted avg       0.83      0.83      0.83        18



In [32]:
# NS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dns['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tns['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ns.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tns['label'], rounded_predictions)
report = classification_report(tns['label'], rounded_predictions)
cm = confusion_matrix(tns['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8333333333333334
[[ 4  1]
 [ 2 11]]
              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.92      0.85      0.88        13

    accuracy                           0.83        18
   macro avg       0.79      0.82      0.80        18
weighted avg       0.85      0.83      0.84        18



In [33]:
# SA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['label'], rounded_predictions)
report = classification_report(tsa['label'], rounded_predictions)
cm = confusion_matrix(tsa['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8333333333333334
[[ 4  1]
 [ 2 11]]
              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.92      0.85      0.88        13

    accuracy                           0.83        18
   macro avg       0.79      0.82      0.80        18
weighted avg       0.85      0.83      0.84        18



In [34]:
# SS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dss['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tss['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ss.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tss['label'], rounded_predictions)
report = classification_report(tss['label'], rounded_predictions)
cm = confusion_matrix(tss['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8333333333333334
[[ 5  0]
 [ 3 10]]
              precision    recall  f1-score   support

           0       0.62      1.00      0.77         5
           1       1.00      0.77      0.87        13

    accuracy                           0.83        18
   macro avg       0.81      0.88      0.82        18
weighted avg       0.90      0.83      0.84        18

