In [5]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [6]:
#Load model
na = tf.keras.models.load_model('n_a.h5')
ns = tf.keras.models.load_model('n_s.h5')
sa = tf.keras.models.load_model('s_a.h5')
ss = tf.keras.models.load_model('s_s.h5')

In [7]:
#load dataset after preprocessing
dna = pd.read_csv('d_na.csv')
dns = pd.read_csv('d_ns.csv')
dsa = pd.read_csv('d_sa.csv')
dss = pd.read_csv('d_ss.csv')

In [8]:
#load data test after preprocessing
tna = pd.read_csv('v_na.csv')
tns = pd.read_csv('v_ns.csv')
tsa = pd.read_csv('v_sa.csv')
tss = pd.read_csv('v_ss.csv')

In [9]:
# NA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dna['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tna['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = na.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tna['label'], rounded_predictions)
report = classification_report(tna['label'], rounded_predictions)
cm = confusion_matrix(tna['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8080808080808081
[[16  8]
 [11 64]]
              precision    recall  f1-score   support

           0       0.59      0.67      0.63        24
           1       0.89      0.85      0.87        75

    accuracy                           0.81        99
   macro avg       0.74      0.76      0.75        99
weighted avg       0.82      0.81      0.81        99



In [10]:
# NS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dns['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tns['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ns.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tns['label'], rounded_predictions)
report = classification_report(tns['label'], rounded_predictions)
cm = confusion_matrix(tns['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8787878787878788
[[20  4]
 [ 8 67]]
              precision    recall  f1-score   support

           0       0.71      0.83      0.77        24
           1       0.94      0.89      0.92        75

    accuracy                           0.88        99
   macro avg       0.83      0.86      0.84        99
weighted avg       0.89      0.88      0.88        99



In [11]:
# SA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['label'], rounded_predictions)
report = classification_report(tsa['label'], rounded_predictions)
cm = confusion_matrix(tsa['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9292929292929293
[[21  3]
 [ 4 71]]
              precision    recall  f1-score   support

           0       0.84      0.88      0.86        24
           1       0.96      0.95      0.95        75

    accuracy                           0.93        99
   macro avg       0.90      0.91      0.91        99
weighted avg       0.93      0.93      0.93        99



In [12]:
# SA
# Preprocess data
ts = ["Tempat nya bersih", "panas tidak tenda", "wisat tutup hujan becek", "bumdes ramah"]
t=[1,0,0,1]
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(ts)
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(t, rounded_predictions)
report = classification_report(t, rounded_predictions)
cm = confusion_matrix(t, rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[2 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [13]:
# SS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dss['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tss['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ss.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tss['label'], rounded_predictions)
report = classification_report(tss['label'], rounded_predictions)
cm = confusion_matrix(tss['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9090909090909091
[[21  3]
 [ 6 69]]
              precision    recall  f1-score   support

           0       0.78      0.88      0.82        24
           1       0.96      0.92      0.94        75

    accuracy                           0.91        99
   macro avg       0.87      0.90      0.88        99
weighted avg       0.91      0.91      0.91        99

