In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [3]:
#Load model
na = tf.keras.models.load_model('n_as.h5')
ns = tf.keras.models.load_model('n_sn.h5')
sa = tf.keras.models.load_model('s_an.h5')
ss = tf.keras.models.load_model('s_sn.h5')

In [4]:
#load dataset after preprocessing
dna = pd.read_csv('data_ap_n_a.csv')
dns = pd.read_csv('data_ap_n_s.csv')
dsa = pd.read_csv('data_ap_s_a.csv')
dss = pd.read_csv('data_ap_s_s.csv')

In [5]:
#load data test after preprocessing
tna = pd.read_csv('v_ap_n_a.csv')
tns = pd.read_csv('v_ap_n_s.csv')
tsa = pd.read_csv('v_ap_s_a.csv')
tss = pd.read_csv('v_ap_s_s.csv')

In [6]:
# NA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dna['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tna['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = na.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tna['label'], rounded_predictions)
report = classification_report(tna['label'], rounded_predictions)
cm = confusion_matrix(tna['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8585858585858586
[[19  8]
 [ 6 66]]
              precision    recall  f1-score   support

           0       0.76      0.70      0.73        27
           1       0.89      0.92      0.90        72

    accuracy                           0.86        99
   macro avg       0.83      0.81      0.82        99
weighted avg       0.86      0.86      0.86        99



In [7]:
# NS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dns['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tns['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ns.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tns['label'], rounded_predictions)
report = classification_report(tns['label'], rounded_predictions)
cm = confusion_matrix(tns['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8484848484848485
[[17 10]
 [ 5 67]]
              precision    recall  f1-score   support

           0       0.77      0.63      0.69        27
           1       0.87      0.93      0.90        72

    accuracy                           0.85        99
   macro avg       0.82      0.78      0.80        99
weighted avg       0.84      0.85      0.84        99



In [8]:
# SA
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['label'], rounded_predictions)
report = classification_report(tsa['label'], rounded_predictions)
cm = confusion_matrix(tsa['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8585858585858586
[[20  7]
 [ 7 65]]
              precision    recall  f1-score   support

           0       0.74      0.74      0.74        27
           1       0.90      0.90      0.90        72

    accuracy                           0.86        99
   macro avg       0.82      0.82      0.82        99
weighted avg       0.86      0.86      0.86        99



In [9]:
# SA
# Preprocess data
ts = ["Tempat nya bersih", "panas tidak tenda", "wisat tutup hujan becek", "bumdes ramah"]
t=[1,0,0,1]
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(ts)
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(t, rounded_predictions)
report = classification_report(t, rounded_predictions)
cm = confusion_matrix(t, rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[2 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [10]:
# SS
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dss['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tss['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = ss.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tss['label'], rounded_predictions)
report = classification_report(tss['label'], rounded_predictions)
cm = confusion_matrix(tss['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9191919191919192
[[24  3]
 [ 5 67]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86        27
           1       0.96      0.93      0.94        72

    accuracy                           0.92        99
   macro avg       0.89      0.91      0.90        99
weighted avg       0.92      0.92      0.92        99

