In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [3]:
#Load model
sa = tf.keras.models.load_model('s_a.h5')
k = tf.keras.models.load_model('sa_k.h5')
w = tf.keras.models.load_model('sa_w.h5')
f = tf.keras.models.load_model('sa_f.h5')
p = tf.keras.models.load_model('sa_p.h5')

In [4]:
#load dataset after preprocessing
dsa = pd.read_csv('d_sa.csv')

In [5]:
# NA
# Preprocess data
data = ["sawah hijau luas mendung", "toilet kotor ember lihat luar"]
label = [1,0]
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(data)
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(label, rounded_predictions)
report = classification_report(label, rounded_predictions)
cm = confusion_matrix(label, rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[1 0]
 [0 1]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



In [6]:
#load data test after preprocessing
tsa = pd.read_csv('v_sa.csv')

In [7]:
# Sentiment
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['label'], rounded_predictions)
report = classification_report(tsa['label'], rounded_predictions)
cm = confusion_matrix(tsa['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9191919191919192
[[19  5]
 [ 3 72]]
              precision    recall  f1-score   support

           0       0.86      0.79      0.83        24
           1       0.94      0.96      0.95        75

    accuracy                           0.92        99
   macro avg       0.90      0.88      0.89        99
weighted avg       0.92      0.92      0.92        99



In [8]:
# Kuliner
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = k.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['kuliner'], rounded_predictions)
report = classification_report(tsa['kuliner'], rounded_predictions)
cm = confusion_matrix(tsa['kuliner'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9494949494949495
[[86  2]
 [ 3  8]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.97        88
           1       0.80      0.73      0.76        11

    accuracy                           0.95        99
   macro avg       0.88      0.85      0.87        99
weighted avg       0.95      0.95      0.95        99



In [10]:
# wahana
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = w.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['wahana'], rounded_predictions)
report = classification_report(tsa['wahana'], rounded_predictions)
cm = confusion_matrix(tsa['wahana'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9191919191919192
[[75  5]
 [ 3 16]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        80
           1       0.76      0.84      0.80        19

    accuracy                           0.92        99
   macro avg       0.86      0.89      0.87        99
weighted avg       0.92      0.92      0.92        99



In [11]:
# pelayanan
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = p.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['pelayanan'], rounded_predictions)
report = classification_report(tsa['pelayanan'], rounded_predictions)
cm = confusion_matrix(tsa['pelayanan'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9393939393939394
[[90  3]
 [ 3  3]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        93
           1       0.50      0.50      0.50         6

    accuracy                           0.94        99
   macro avg       0.73      0.73      0.73        99
weighted avg       0.94      0.94      0.94        99



In [12]:
# fasilitas
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = f.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['fasilitas'], rounded_predictions)
report = classification_report(tsa['fasilitas'], rounded_predictions)
cm = confusion_matrix(tsa['fasilitas'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.8181818181818182
[[59 14]
 [ 4 22]]
              precision    recall  f1-score   support

           0       0.94      0.81      0.87        73
           1       0.61      0.85      0.71        26

    accuracy                           0.82        99
   macro avg       0.77      0.83      0.79        99
weighted avg       0.85      0.82      0.83        99

