In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
#Load model
sa = tf.keras.models.load_model('s_a.h5')
k = tf.keras.models.load_model('sa_k.h5')
w = tf.keras.models.load_model('sa_w.h5')
f = tf.keras.models.load_model('sa_f.h5')
p = tf.keras.models.load_model('sa_p.h5')

In [5]:
#load dataset after preprocessing
dsa = pd.read_csv('d_sa.csv')

In [6]:
# NA
# Preprocess data
data = ["sawah hijau luas mendung", "toilet kotor ember lihat luar"]
label = [1,0]
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(data)
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(label, rounded_predictions)
report = classification_report(label, rounded_predictions)
cm = confusion_matrix(label, rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[1 0]
 [0 1]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



In [7]:
#load data test after preprocessing
tsa = pd.read_csv('dum_ap_kebalik_t.csv')

In [8]:
# Sentiment
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = sa.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['label'], rounded_predictions)
report = classification_report(tsa['label'], rounded_predictions)
cm = confusion_matrix(tsa['label'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9
[[6 0]
 [1 3]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      0.75      0.86         4

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10



In [9]:
# Kuliner
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = k.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['kuliner'], rounded_predictions)
report = classification_report(tsa['kuliner'], rounded_predictions)
cm = confusion_matrix(tsa['kuliner'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[7 0]
 [0 3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         3

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [11]:
# wahana
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = w.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['wahana '], rounded_predictions)
report = classification_report(tsa['wahana '], rounded_predictions)
cm = confusion_matrix(tsa['wahana '], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 0.9
[[6 0]
 [1 3]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      0.75      0.86         4

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10



In [12]:
# pelayanan
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = p.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['pelayanan'], rounded_predictions)
report = classification_report(tsa['pelayanan'], rounded_predictions)
cm = confusion_matrix(tsa['pelayanan'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[8 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         2

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [13]:
# fasilitas
# Preprocess data
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(dsa['Ulasan'].astype(str))
X = tokenizer.texts_to_sequences(tsa['ulasan'].astype(str))
X = pad_sequences(X, maxlen=50, padding='post')

# Make predictions
predictions = f.predict(X)
rounded_predictions = np.round(predictions).astype(int)

accuracy = accuracy_score(tsa['fasilitas'], rounded_predictions)
report = classification_report(tsa['fasilitas'], rounded_predictions)
cm = confusion_matrix(tsa['fasilitas'], rounded_predictions)

print('Accuracy:', accuracy)
print(cm)
print(report)

Accuracy: 1.0
[[5 0]
 [0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

